name: Dispatch Workflow

on:
  workflow_dispatch:

env:
  OUTPUT_DIR: "${{ github.workspace }}/output"
  DEVELOPER_DIR: /Applications/Xcode_12.5.1.app/Contents/Developer
  DERIVED_DATA: DerivedData

jobs:
  cleanup-runs:
    name: Clean up previously running instances of a workflow on the same branch
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  simulator-record:
   name: Simulator Record
   runs-on: macos-11

   steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Make Output Directory
      run: |
        mkdir -p ${{ env.OUTPUT_DIR }}
        mkdir -p ${{ env.OUTPUT_DIR }}/records

    - name: Select Xcode
      run: |
        xcodebuild -version
        sudo xcode-select --switch ${{ env.DEVELOPER_DIR }}
        xcodebuild -version

    - name: Extract Simulator
      run: |
        xcrun xctrace list devices 2>&1 | \
        grep -v Apple | \
        grep "iPhone 11 (14.5)" | \
        sed -n "1,1p" | \
        sed -r "s/^.*\(([-0-9ABCDEF]+)\)$/\1/" | \
        xargs -Iid echo "DEVICE_ID=id" >> $GITHUB_ENV

    - name: Build For Test
      run: |
        xcodebuild clean build-for-testing \
        -project UITestPractice.xcodeproj \
        -scheme UITestPractice \
        -destination "platform=iOS Simulator,id=${{ env.DEVICE_ID }}" \
        -derivedDataPath ${{ env.DERIVED_DATA }}

    - name: UITest Without Building
      run: |
        xcodebuild -version
        open ${{ env.DEVELOPER_DIR }}/Applications/Simulator.app
        xcrun simctl bootstatus ${{ env.DEVICE_ID }} -b
        xcrun simctl io "${{ env.DEVICE_ID }}" recordVideo --force --display=internal ${{ env.OUTPUT_DIR }}/records/iphone.mov > /dev/null 2>&1 &
        RECORD_PID=$!
        xcodebuild test-without-building \
        -project UITestPractice.xcodeproj \
        -scheme UITestPractice \
        -destination "platform=iOS Simulator,id=${{ env.DEVICE_ID }}" \
        -derivedDataPath ${{ env.DERIVED_DATA }} \
        -only-testing:UITestPracticeUITests
        echo $RECORD_PID
        kill -SIGINT $RECORD_PID

    - name: Store Test Result Directory
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: Test Result
        path: ${{ env.OUTPUT_DIR }}
        retention-days: 3
